/* Auto-generated by GitHub Actions. Do not edit by hand. */
window.BRIEFING = {
  "date": "Wednesday, October 7, 2026",
  "asOf": "Live figures, latest available close",
  "updated": "Oct 7, 2026 · 7:00 AM ICT",
  "topStory": "US equities rose sharply in the latest session, with the Nasdaq rose sharply. Crude fell sharply and gold fell sharply. See the sections below for the full board; your 7:00 AM briefing has the detailed analysis.",
  "sections": [
    {
      "icon": "🇺🇸",
      "title": "US Markets",
      "span": false,
      "rows": [
        {
          "name": "S&P 500",
          "lvl": "7,818.93",
          "chg": "+1.9%",
          "dir": "up"
        },
        {
          "name": "Nasdaq Composite",
          "lvl": "27,599.89",
          "chg": "+3.0%",
          "dir": "up"
        },
        {
          "name": "Dow Jones",
          "lvl": "51,521.30",
          "chg": "+0.3%",
          "dir": "up"
        },
        {
          "name": "PHLX Semis (SOX)",
          "lvl": "13,217.82",
          "chg": "+4.7%",
          "dir": "up"
        }
      ],
      "note": "Index levels and daily change from the most recent session."
    },
    {
      "icon": "🌏",
      "title": "Asia-Pacific",
      "span": false,
      "rows": [
        {
          "name": "Nikkei 225 (Tokyo)",
          "lvl": "70,074.13",
          "chg": "+1.6%",
          "dir": "up"
        },
        {
          "name": "Hang Seng",
          "lvl": "24,135.88",
          "chg": "-1.6%",
          "dir": "down"
        },
        {
          "name": "Shanghai Composite",
          "lvl": "3,842.20",
          "chg": "-2.4%",
          "dir": "down"
        },
        {
          "name": "Kospi (Seoul)",
          "lvl": "6,870.93",
          "chg": "+0.0%",
          "dir": "flat"
        }
      ],
      "note": "Regional benchmarks; some markets may be closed for local holidays."
    },
    {
      "icon": "🇪🇺",
      "title": "Europe & Global",
      "span": false,
      "rows": [
        {
          "name": "FTSE 100",
          "lvl": "10,541.69",
          "chg": "-0.9%",
          "dir": "down"
        },
        {
          "name": "DAX",
          "lvl": "25,449.19",
          "chg": "+0.2%",
          "dir": "up"
        }
      ],
      "note": "Major European benchmarks."
    },
    {
      "icon": "💻",
      "title": "Tech / AI Theme",
      "span": false,
      "rows": [],
      "note": "The Nasdaq rose sharply and the PHLX Semiconductor index rose sharply — the clearest read on the day's AI/chip sentiment. Watch the US open for direction."
    },
    {
      "icon": "💵",
      "title": "FX & Rates",
      "span": false,
      "rows": [
        {
          "name": "US 10-yr Treasury",
          "lvl": "5.27%",
          "chg": "-0.5%",
          "dir": "down"
        },
        {
          "name": "USD/THB",
          "lvl": "33.63",
          "chg": "+0.1%",
          "dir": "up"
        },
        {
          "name": "USD/JPY",
          "lvl": "158.38",
          "chg": "+0.5%",
          "dir": "up"
        },
        {
          "name": "EUR/USD",
          "lvl": "1.1241",
          "chg": "-0.8%",
          "dir": "down"
        },
        {
          "name": "Dollar Index (DXY)",
          "lvl": "102.03",
          "chg": "-0.1%",
          "dir": "down"
        }
      ],
      "note": "US 10-year Treasury yield, key USD pairs, and the dollar index."
    },
    {
      "icon": "🛢️",
      "title": "Commodities",
      "span": false,
      "rows": [
        {
          "name": "WTI Crude",
          "lvl": "$90.16",
          "chg": "-2.9%",
          "dir": "down"
        },
        {
          "name": "Brent Crude",
          "lvl": "$101.55",
          "chg": "-0.7%",
          "dir": "down"
        },
        {
          "name": "Gold",
          "lvl": "$4,169.90",
          "chg": "-0.8%",
          "dir": "down"
        }
      ],
      "note": "WTI and Brent crude, and spot gold futures."
    },
    {
      "icon": "📅",
      "title": "Macro Watch",
      "span": true,
      "rows": [],
      "note": "Watch central-bank commentary, scheduled inflation/jobs data, and major geopolitical headlines. Your full 7:00 AM briefing covers the day's specific catalysts."
    }
  ],
  "sources": [
    {
      "label": "Yahoo Finance — Markets",
      "url": "https://finance.yahoo.com/markets/"
    },
    {
      "label": "CNBC Markets",
      "url": "https://www.cnbc.com/markets/"
    },
    {
      "label": "Trading Economics",
      "url": "https://tradingeconomics.com/"
    }
  ]
};
