/* Auto-generated by GitHub Actions. Do not edit by hand. */
window.BRIEFING = {
  "date": "Wednesday, July 22, 2026",
  "asOf": "Live figures, latest available close",
  "updated": "Jul 22, 2026 · 7:00 AM ICT",
  "topStory": "US equities edged lower in the latest session, with the Nasdaq fell sharply. Crude rose sharply and gold rose sharply. See the sections below for the full board; your 7:00 AM briefing has the detailed analysis.",
  "sections": [
    {
      "icon": "🇺🇸",
      "title": "US Markets",
      "span": false,
      "rows": [
        {
          "name": "S&P 500",
          "lvl": "7,509.20",
          "chg": "-0.5%",
          "dir": "down"
        },
        {
          "name": "Nasdaq Composite",
          "lvl": "25,837.21",
          "chg": "-1.0%",
          "dir": "down"
        },
        {
          "name": "Dow Jones",
          "lvl": "52,224.64",
          "chg": "-0.5%",
          "dir": "down"
        },
        {
          "name": "PHLX Semis (SOX)",
          "lvl": "12,356.16",
          "chg": "-2.4%",
          "dir": "down"
        }
      ],
      "note": "Index levels and daily change from the most recent session."
    },
    {
      "icon": "🌏",
      "title": "Asia-Pacific",
      "span": false,
      "rows": [
        {
          "name": "Nikkei 225 (Tokyo)",
          "lvl": "66,115.60",
          "chg": "-3.8%",
          "dir": "down"
        },
        {
          "name": "Hang Seng",
          "lvl": "24,892.66",
          "chg": "+0.9%",
          "dir": "up"
        },
        {
          "name": "Shanghai Composite",
          "lvl": "3,867.03",
          "chg": "-0.4%",
          "dir": "down"
        },
        {
          "name": "Kospi (Seoul)",
          "lvl": "6,797.70",
          "chg": "-0.9%",
          "dir": "down"
        }
      ],
      "note": "Regional benchmarks; some markets may be closed for local holidays."
    },
    {
      "icon": "🇪🇺",
      "title": "Europe & Global",
      "span": false,
      "rows": [
        {
          "name": "FTSE 100",
          "lvl": "10,708.20",
          "chg": "+1.8%",
          "dir": "up"
        },
        {
          "name": "DAX",
          "lvl": "25,185.44",
          "chg": "+0.7%",
          "dir": "up"
        }
      ],
      "note": "Major European benchmarks."
    },
    {
      "icon": "💻",
      "title": "Tech / AI Theme",
      "span": false,
      "rows": [],
      "note": "The Nasdaq fell sharply and the PHLX Semiconductor index fell sharply — the clearest read on the day's AI/chip sentiment. Watch the US open for direction."
    },
    {
      "icon": "💵",
      "title": "FX & Rates",
      "span": false,
      "rows": [
        {
          "name": "US 10-yr Treasury",
          "lvl": "4.63%",
          "chg": "+1.8%",
          "dir": "up"
        },
        {
          "name": "USD/THB",
          "lvl": "33.78",
          "chg": "+0.7%",
          "dir": "up"
        },
        {
          "name": "USD/JPY",
          "lvl": "162.97",
          "chg": "+0.6%",
          "dir": "up"
        },
        {
          "name": "EUR/USD",
          "lvl": "1.1412",
          "chg": "-0.5%",
          "dir": "down"
        },
        {
          "name": "Dollar Index (DXY)",
          "lvl": "101.10",
          "chg": "+0.3%",
          "dir": "up"
        }
      ],
      "note": "US 10-year Treasury yield, key USD pairs, and the dollar index."
    },
    {
      "icon": "🛢️",
      "title": "Commodities",
      "span": false,
      "rows": [
        {
          "name": "WTI Crude",
          "lvl": "$87.34",
          "chg": "+5.9%",
          "dir": "up"
        },
        {
          "name": "Brent Crude",
          "lvl": "$94.06",
          "chg": "+6.8%",
          "dir": "up"
        },
        {
          "name": "Gold",
          "lvl": "$4,126.00",
          "chg": "+2.8%",
          "dir": "up"
        }
      ],
      "note": "WTI and Brent crude, and spot gold futures."
    },
    {
      "icon": "📅",
      "title": "Macro Watch",
      "span": true,
      "rows": [],
      "note": "Watch central-bank commentary, scheduled inflation/jobs data, and major geopolitical headlines. Your full 7:00 AM briefing covers the day's specific catalysts."
    }
  ],
  "sources": [
    {
      "label": "Yahoo Finance — Markets",
      "url": "https://finance.yahoo.com/markets/"
    },
    {
      "label": "CNBC Markets",
      "url": "https://www.cnbc.com/markets/"
    },
    {
      "label": "Trading Economics",
      "url": "https://tradingeconomics.com/"
    }
  ]
};
