/* Auto-generated by GitHub Actions. Do not edit by hand. */
window.BRIEFING = {
  "date": "Thursday, July 23, 2026",
  "asOf": "Live figures, latest available close",
  "updated": "Jul 23, 2026 · 7:00 AM ICT",
  "topStory": "US equities fell sharply in the latest session, with the Nasdaq fell sharply. Crude rose sharply and gold rose sharply. See the sections below for the full board; your 7:00 AM briefing has the detailed analysis.",
  "sections": [
    {
      "icon": "🇺🇸",
      "title": "US Markets",
      "span": false,
      "rows": [
        {
          "name": "S&P 500",
          "lvl": "7,498.96",
          "chg": "-1.0%",
          "dir": "down"
        },
        {
          "name": "Nasdaq Composite",
          "lvl": "25,690.90",
          "chg": "-2.2%",
          "dir": "down"
        },
        {
          "name": "Dow Jones",
          "lvl": "52,218.58",
          "chg": "-0.8%",
          "dir": "down"
        },
        {
          "name": "PHLX Semis (SOX)",
          "lvl": "12,410.67",
          "chg": "+0.1%",
          "dir": "up"
        }
      ],
      "note": "Index levels and daily change from the most recent session."
    },
    {
      "icon": "🌏",
      "title": "Asia-Pacific",
      "span": false,
      "rows": [
        {
          "name": "Nikkei 225 (Tokyo)",
          "lvl": "66,422.60",
          "chg": "-0.6%",
          "dir": "down"
        },
        {
          "name": "Hang Seng",
          "lvl": "25,210.81",
          "chg": "+0.8%",
          "dir": "up"
        },
        {
          "name": "Shanghai Composite",
          "lvl": "3,876.78",
          "chg": "+3.0%",
          "dir": "up"
        },
        {
          "name": "Kospi (Seoul)",
          "lvl": "7,096.89",
          "chg": "-2.6%",
          "dir": "down"
        }
      ],
      "note": "Regional benchmarks; some markets may be closed for local holidays."
    },
    {
      "icon": "🇪🇺",
      "title": "Europe & Global",
      "span": false,
      "rows": [
        {
          "name": "FTSE 100",
          "lvl": "10,699.36",
          "chg": "+1.2%",
          "dir": "up"
        },
        {
          "name": "DAX",
          "lvl": "25,030.31",
          "chg": "+0.5%",
          "dir": "up"
        }
      ],
      "note": "Major European benchmarks."
    },
    {
      "icon": "💻",
      "title": "Tech / AI Theme",
      "span": false,
      "rows": [],
      "note": "The Nasdaq fell sharply and the PHLX Semiconductor index edged higher — the clearest read on the day's AI/chip sentiment. Watch the US open for direction."
    },
    {
      "icon": "💵",
      "title": "FX & Rates",
      "span": false,
      "rows": [
        {
          "name": "US 10-yr Treasury",
          "lvl": "4.66%",
          "chg": "+1.9%",
          "dir": "up"
        },
        {
          "name": "USD/THB",
          "lvl": "33.78",
          "chg": "+0.7%",
          "dir": "up"
        },
        {
          "name": "USD/JPY",
          "lvl": "163.36",
          "chg": "+0.6%",
          "dir": "up"
        },
        {
          "name": "EUR/USD",
          "lvl": "1.1416",
          "chg": "-0.3%",
          "dir": "down"
        },
        {
          "name": "Dollar Index (DXY)",
          "lvl": "101.11",
          "chg": "+0.1%",
          "dir": "up"
        }
      ],
      "note": "US 10-year Treasury yield, key USD pairs, and the dollar index."
    },
    {
      "icon": "🛢️",
      "title": "Commodities",
      "span": false,
      "rows": [
        {
          "name": "WTI Crude",
          "lvl": "$89.41",
          "chg": "+7.4%",
          "dir": "up"
        },
        {
          "name": "Brent Crude",
          "lvl": "$86.41",
          "chg": "-3.1%",
          "dir": "down"
        },
        {
          "name": "Gold",
          "lvl": "$4,101.50",
          "chg": "+2.3%",
          "dir": "up"
        }
      ],
      "note": "WTI and Brent crude, and spot gold futures."
    },
    {
      "icon": "📅",
      "title": "Macro Watch",
      "span": true,
      "rows": [],
      "note": "Watch central-bank commentary, scheduled inflation/jobs data, and major geopolitical headlines. Your full 7:00 AM briefing covers the day's specific catalysts."
    }
  ],
  "sources": [
    {
      "label": "Yahoo Finance — Markets",
      "url": "https://finance.yahoo.com/markets/"
    },
    {
      "label": "CNBC Markets",
      "url": "https://www.cnbc.com/markets/"
    },
    {
      "label": "Trading Economics",
      "url": "https://tradingeconomics.com/"
    }
  ]
};
